### ISSUE TITLE
Area, bar,.. plot are rendered as line plot when no options argument is specified.

### ISSUE THREAD

**Issue by matsvandecavey** [arnoutaertgeerts/python-highcharts#14]
When making a different type of plot like 'bar', 'area', 'spline' the type remains a line plot if the default options in charts.plot( ) are used.
Only when charts.plot('type'='<type>', options={ } ) options argument (can be empty dict) is specified, the chart is plotted as the correct type.
I will try and fix this with a pull request.

**Comment by arnoutaertgeerts** [comment]
Fixed in version 0.2.1 https://github.com/arnoutaertgeerts/python-highcharts/commit/6377b790505ed8e461b086cf0ce05334f6f6753d
