### ISSUE TITLE
Dataframe series limitation example fails

### ISSUE THREAD

**Issue by Ryton** [arnoutaertgeerts/python-highcharts#22]
While the Dataframe ipython notebook is a good intro to pandas visualisation with highcharts,
 the demo workbook fails to limit the number of shown lines to 3 (from 26) for me, on windows 8, python 2.7 & ipython ...3.0?

For some reason, the display = ['A','G','Z'] option is ignored
See attachment
![dataframe_26_lines](https://cloud.githubusercontent.com/assets/6223082/8109092/4118206c-1055-11e5-810e-13f40ba2c943.jpg)

**Comment by arnoutaertgeerts** [comment]
@Ryton Try putting the display option in the `charts.plot()` method. That should do the trick :) 

The pandas dataframe tutorial is indeed outdated, I will remove it to avoid confusion. Now you can directly plot dataframes as is shown in the main tutorial [here](http://nbviewer.ipython.org/github/arnoutaertgeerts/python-highcharts/blob/master/Tutorial.ipynb) at line 5:

``` python
charts.plot(df, options, height=500, stock=True, show='inline', display=['A', 'G', 'Z']) 
```

So you don't need to convert it first.

Let me know if that works for you!

**Comment by Ryton** [comment]
Ah, thanks! 
I tried out that main tutoial last week, but thought that this "dataframe.pynb" was a newer version.  My mistake.

Great work! I'm looking forward to plotting my own data with it!
