### ISSUE TITLE
Bug with plot

### ISSUE THREAD

**Issue by damienpicard** [arnoutaertgeerts/python-highcharts#23]
The new version of charts lead to a much longer calculation time for plot! Furthermore, when I try to plot more than 2 plots, the whole notebook crashs...

**Comment by matsvandecavey** [comment]
So far, I have not experienced this problem, Damien

**Comment by damienpicard** [comment]
Apparently my file is too big for a single page. Plotting in _tab_ instead of _inline_ solves the problem.

**Comment by matsvandecavey** [comment]
Try charts.plotasync().
This should be able to handle larger files, rigtht? @arnoutaertgeerts

**Comment by arnoutaertgeerts** [comment]
Yep. Although I also fixed a bug in the `df_to_series()` method which should increase the conversion speed substantially. This will be implemented in the next version.
