### ISSUE TITLE
Save graphs using code

### ISSUE THREAD

**Issue by damienpicard** [arnoutaertgeerts/python-highcharts#25]
Is it possible to save a graph as an image or .pdf directly from the code? Or do you always need the button _save_ ?

**Comment by arnoutaertgeerts** [comment]
This is possible but currently you can only save .svg images. In synchronous mode, just set the `save` option to a string containing your filename with the `.svg` extension, e.g.:

``` python
charts.plot(series, save='my-chart.svg')
```
