### ISSUE TITLE
functionality to change defaults for charts.plot()

### ISSUE THREAD

**Issue by matsvandecavey** [arnoutaertgeerts/python-highcharts#30]
e.g. I prefer having `show='inline'` and `stock=True`

**Comment by arnoutaertgeerts** [comment]
@matsvandecavey You can change your preferences by updating the `default_settings` dictionary. e.g.:

``` python
charts.default_settings.update(dict(show='inline', stock=True))
```

This will update the default settings the module uses. This currently only works for the `plot()` method and cannot be used to set a default `options` dictionary.

I know this should be documented :)

**Comment by matsvandecavey** [comment]
`charts.default_settings.update({'show':'inline'})` is not working:

> AttributeError: 'module' object has no attribute 'default_settings'

**Comment by arnoutaertgeerts** [comment]
Hmm... Did you update to version 0.4.2?

**Comment by matsvandecavey** [comment]
I am on 0.4.2, but still no `charts.default_settings`.

**Comment by matsvandecavey** [comment]
My apologies.. I was using pip to update, but I have the git version on my python path as well.
This prevented me from finding the new version.

Thx Arnout
