### ISSUE TITLE
dataframe cannot be plotted if columns are not of the same type

### ISSUE THREAD

**Issue by matsvandecavey** [arnoutaertgeerts/python-highcharts#31]
This is not a problem as such, but the error message is not comprehensive:

for a pandas.DataFrame df:

> <class 'pandas.core.frame.DataFrame'>
> Int64Index: 160 entries, 0 to 159
> Data columns (total 4 columns):
> Tsupply    160 non-null int64
> PLR        160 non-null float64
> Texair     160 non-null int64
> eta HHV    160 non-null float64
> dtypes: float64(2), int64(2)
> memory usage: 6.2 KB

I get the  following error message for `chart.plot(df)`:

> IndexError                                Traceback (most recent call last)
> <ipython-input-31-7bf9be85cd93> in <module>()
> ----> 1 charts.plot(df)
> 
> D:\work\Python\python-highcharts\charts\plot.pyc in plot(series, options, type, name, height, 
> save, stock, show, display)
>      64         inline = MyTemplate(html.read()).substitute(
>      65             path=package_directory,
> ---> 66             series=json.dumps(series, cls=ChartsJSONEncoder),
>      67             options=json.dumps(options),
>      68             highstock=json.dumps(stock),
> 
> ...
> 
> IndexError: tuple index out of range

I'm not sure which types can be plotted, but having a mixture of the types certainly can't.
If you convert the dataframe `df` using `df.as_types(<type>)` to either `float` or `int` the plot works. Having the combination doesn't.

A simple check should imform the user the dataframe is not in the correct format.

**Comment by arnoutaertgeerts** [comment]
@matsvandecavey Could you provide me with the full error message?

**Comment by matsvandecavey** [comment]
Arnout, I can't quite reproduce it.
It happened after putting together dataframes from different origins, so I guess it was related to the data and not to the type.

Thx for checking
