### ISSUE TITLE
Add ability to generate charts without opening them immediately

### ISSUE THREAD

**Issue by howe1rp** [arnoutaertgeerts/python-highcharts#33]
It would be useful to be able to generate the charts and have them not open automatically upon completion. Useful for workflows where the charts need to be updated, but it's not important to view them right away.

**Comment by arnoutaertgeerts** [comment]
@howe1rp I agree this is a useful feature. I'll look into it.

**Comment by arnoutaertgeerts** [comment]
@howe1rp https://github.com/arnoutaertgeerts/python-highcharts/releases/tag/0.4.3 should fix this! 
You can install this version with

```
pip install charts --upgrade
```

**Comment by howe1rp** [comment]
Perfect! It works! Fantastic tool, thanks again.

**Comment by arnoutaertgeerts** [comment]
@howe1rp Glad it worked!
