### ISSUE TITLE
Version 0.4.4 Does not work

### ISSUE THREAD

**Issue by architkhosla** [arnoutaertgeerts/python-highcharts#36]
A simple plot does not show up in version 0.4.4 but does in 0.4.3

Executed the following code (This is taken from one of your tutorials but changed inline to tab) 

import charts
series = [1,2,3,2,1]
charts.plot(series, show='tab', name='List')

Output: 
Blank page with an empty text box and the settings button which does nothing if clicked.

0.4.3 had this working!
Running on MAC Yosemite.

**Comment by arnoutaertgeerts** [comment]
Yes you are right. I'll fix this as soon as possible!

**Comment by arnoutaertgeerts** [comment]
@architkhosla This should be fixed in version 0.4.5 (The current version on Pypi)
