### ISSUE TITLE
'display' = True option not possible

### ISSUE THREAD

**Issue by Ryton** [arnoutaertgeerts/python-highcharts#41]
when running the example code in notebook (i know it's partially obsolete)

> import pandas as pd
> import numpy as np
> start = pd.Timestamp("20150101")
> end = pd.Timestamp("20150201")
> index = pd.DatetimeIndex(freq='900S', start=start, end=end)
> columns = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 
> 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
> data = np.zeros((26, len(index)))
> for i, c in enumerate(columns):
>     data[i] = i*np.linspace(0, 100, len(index))
> df = pd.DataFrame(index=index, columns=columns, data=data.T)
> options = {
>     'title': {'text': 'An entire pandas dataframe'}
> }
> charts.plot(df, options=options, show='inline',stock=True)'

i get following error:

> <dir>\charts\plot.pyc in plot(series, options, height, save, stock, show)
>      36     for serie in series:
>      37         if 'display' not in serie:
> ---> 38             serie['display'] = True
>      39 
>      40     with open(os.path.join(package_directory, "index.html"), "r") as html:
> TypeError: 'str' object does not support item assignment '

df.plot() works fine. Any hints on how to resolve this issue?

**Comment by Ryton** [comment]
i tried adding 'display':'A' ,  'display':{['A']} and  'display':{'A'}, in the options, but to no avail

**Comment by arnoutaertgeerts** [comment]
@Ryton which notebook is this?

**Comment by Ryton** [comment]
Sorry for the late reply. it was in "tutorial.ipynb" 
But it seems i was still working in an old example, cloning solved the issue.

Sorry, this issue can be closed.
